# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:03:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class DoubleRange(BaseModel):
    end: Optional[float] = Field(None, description='end of the range (exclusive)')
    start: Optional[float] = Field(None, description='start of the range (inclusive)')


class DynamicCluster(BaseModel):
    cluster: Optional[Dict[str, Any]] = Field(None, description='The cluster config.')
    lastUpdated: Optional[str] = Field(
        None, description='The timestamp when the Cluster was last updated.'
    )
    versionInfo: Optional[str] = Field(
        None,
        description='This is the per-resource version information. This version is currently taken from the :ref:`version_info ` field at the time that the cluster was loaded. In the future, discrete per-cluster versions may be supported by the API.',
    )


class DynamicListenerState(BaseModel):
    lastUpdated: Optional[str] = Field(
        None,
        description='The timestamp when the Listener was last successfully updated.',
    )
    listener: Optional[Dict[str, Any]] = Field(None, description='The listener config.')
    versionInfo: Optional[str] = Field(
        None,
        description='This is the per-resource version information. This version is currently taken from the :ref:`version_info ` field at the time that the listener was loaded. In the future, discrete per-listener versions may be supported by the API.',
    )


class DynamicRouteConfig(BaseModel):
    lastUpdated: Optional[str] = Field(
        None, description='The timestamp when the Route was last updated.'
    )
    routeConfig: Optional[Dict[str, Any]] = Field(None, description='The route config.')
    versionInfo: Optional[str] = Field(
        None,
        description='This is the per-resource version information. This version is currently taken from the :ref:`version_info ` field at the time that the route configuration was loaded.',
    )


class DynamicScopedRouteConfigs(BaseModel):
    lastUpdated: Optional[str] = Field(
        None,
        description='The timestamp when the scoped route config set was last updated.',
    )
    name: Optional[str] = Field(
        None, description='The name assigned to the scoped route configurations.'
    )
    scopedRouteConfigs: Optional[List[Dict[str, Any]]] = Field(
        None, description='The scoped route configurations.'
    )
    versionInfo: Optional[str] = Field(
        None,
        description='This is the per-resource version information. This version is currently taken from the :ref:`version_info ` field at the time that the scoped routes configuration was loaded.',
    )


class GoogleRE2(BaseModel):
    maxProgramSize: Optional[int] = Field(
        None,
        description='This field controls the RE2 "program size" which is a rough estimate of how complex a compiled regex is to evaluate. A regex that has a program size greater than the configured value will fail to compile. In this case, the configured max program size can be increased or the regex can be simplified. If not specified, the default is 100. This field is deprecated; regexp validation should be performed on the management server instead of being done by each individual client.',
    )


class InlineScopedRouteConfigs(BaseModel):
    lastUpdated: Optional[str] = Field(
        None,
        description='The timestamp when the scoped route config set was last updated.',
    )
    name: Optional[str] = Field(
        None, description='The name assigned to the scoped route configurations.'
    )
    scopedRouteConfigs: Optional[List[Dict[str, Any]]] = Field(
        None, description='The scoped route configurations.'
    )


class Locality(BaseModel):
    region: Optional[str] = Field(
        None, description='Region this :ref:`zone ` belongs to.'
    )
    subZone: Optional[str] = Field(
        None,
        description='When used for locality of upstream hosts, this field further splits zone into smaller chunks of sub-zones so they can be load balanced independently.',
    )
    zone: Optional[str] = Field(
        None,
        description='Defines the local service zone where Envoy is running. Though optional, it should be set if discovery service routing is used and the discovery service exposes :ref:`zone data `, either in this message or via :option:`--service-zone`. The meaning of zone is context dependent, e.g. `Availability Zone (AZ) `_ on AWS, `Zone `_ on GCP, etc.',
    )


class NullMatch(BaseModel):
    pass


class PathSegment(BaseModel):
    key: Optional[str] = Field(
        None, description='If specified, use the key to retrieve the value in a Struct.'
    )


class Status(Enum):
    UNKNOWN = 'UNKNOWN'
    SYNCED = 'SYNCED'
    NOT_SENT = 'NOT_SENT'
    STALE = 'STALE'
    ERROR = 'ERROR'


class Pipe(BaseModel):
    mode: Optional[int] = Field(
        None, description='The mode for the Pipe. Not applicable for abstract sockets.'
    )
    path: Optional[str] = Field(
        None,
        description="Unix Domain Socket path. On Linux, paths starting with '@' will use the abstract namespace. The starting '@' is replaced by a null byte by Envoy. Paths starting with '@' will result in an error in environments other than Linux.",
    )


class RegexMatcher(BaseModel):
    googleRe2: Optional[GoogleRE2] = Field(
        None, description="Google's RE2 regex engine."
    )
    regex: Optional[str] = Field(
        None,
        description='The regex match string. The string must be supported by the configured engine.',
    )


class ScopedRoutesConfigDump(BaseModel):
    dynamicScopedRouteConfigs: Optional[List[DynamicScopedRouteConfigs]] = Field(
        None, description='The dynamically loaded scoped route configs.'
    )
    inlineScopedRouteConfigs: Optional[List[InlineScopedRouteConfigs]] = Field(
        None, description='The statically loaded scoped route configs.'
    )


class SemanticVersion(BaseModel):
    majorNumber: Optional[int] = None
    minorNumber: Optional[int] = None
    patch: Optional[int] = None


class Protocol(Enum):
    TCP = 'TCP'
    UDP = 'UDP'


class SocketAddress(BaseModel):
    address: Optional[str] = Field(
        None,
        description='The address for this socket. :ref:`Listeners ` will bind to the address. An empty address is not allowed. Specify ``0.0.0.0`` or ``::`` to bind to any address. [#comment:TODO(zuercher) reinstate when implemented: It is possible to distinguish a Listener address via the prefix/suffix matching in :ref:`FilterChainMatch `.] When used within an upstream :ref:`BindConfig `, the address controls the source address of outbound connections. For :ref:`clusters `, the cluster type determines whether the address must be an IP (*STATIC* or *EDS* clusters) or a hostname resolved by DNS (*STRICT_DNS* or *LOGICAL_DNS* clusters). Address resolution can be customized via :ref:`resolver_name `.',
    )
    ipv4Compat: Optional[bool] = Field(
        None,
        description='When binding to an IPv6 address above, this enables `IPv4 compatibility `_. Binding to ``::`` will allow both IPv4 and IPv6 connections, with peer IPv4 addresses mapped into IPv6 space as ``::FFFF:``.',
    )
    namedPort: Optional[str] = Field(
        None,
        description='This is only valid if :ref:`resolver_name ` is specified below and the named resolver is capable of named port resolution.',
    )
    portValue: Optional[int] = None
    protocol: Optional[Protocol] = None
    resolverName: Optional[str] = Field(
        None,
        description='The name of the custom resolver. This must have been registered with Envoy. If this is empty, a context dependent default applies. If the address is a concrete IP address, no resolution will occur. If address is a hostname this should be set for resolution other than DNS. Specifying a custom resolver with *STRICT_DNS* or *LOGICAL_DNS* will generate an error at runtime.',
    )


class StaticCluster(BaseModel):
    cluster: Optional[Dict[str, Any]] = Field(None, description='The cluster config.')
    lastUpdated: Optional[str] = Field(
        None, description='The timestamp when the Cluster was last updated.'
    )


class StaticListener(BaseModel):
    lastUpdated: Optional[str] = Field(
        None,
        description='The timestamp when the Listener was last successfully updated.',
    )
    listener: Optional[Dict[str, Any]] = Field(None, description='The listener config.')


class StaticRouteConfig(BaseModel):
    lastUpdated: Optional[str] = Field(
        None, description='The timestamp when the Route was last updated.'
    )
    routeConfig: Optional[Dict[str, Any]] = Field(None, description='The route config.')


class StringMatcher(BaseModel):
    exact: Optional[str] = Field(
        None,
        description='The input string must match exactly the string specified here. Examples: * *abc* only matches the value *abc*.',
    )
    ignoreCase: Optional[bool] = Field(
        None,
        description='If true, indicates the exact/prefix/suffix matching should be case insensitive. This has no effect for the safe_regex match. For example, the matcher *data* will match both input string *Data* and *data* if set to true.',
    )
    prefix: Optional[str] = Field(
        None,
        description='The input string must have the prefix specified here. Note: empty prefix is not allowed, please use regex instead. Examples: * *abc* matches the value *abc.xyz*',
    )
    regex: Optional[str] = Field(
        None,
        description='The input string must match the regular expression specified here. The regex grammar is defined `here `_. Examples: * The regex ``\\d{3}`` matches the value *123* * The regex ``\\d{3}`` does not match the value *1234* * The regex ``\\d{3}`` does not match the value *123.456* .. attention:: This field has been deprecated in favor of `safe_regex` as it is not safe for use with untrusted input in all cases.',
    )
    safeRegex: Optional[RegexMatcher] = Field(
        None,
        description='The input string must match the regular expression specified here.',
    )
    suffix: Optional[str] = Field(
        None,
        description='The input string must have the suffix specified here. Note: empty prefix is not allowed, please use regex instead. Examples: * *abc* matches the value *xyz.abc*',
    )


class UpdateFailureState(BaseModel):
    details: Optional[str] = Field(
        None, description='Details about the last failed update attempt.'
    )
    failedConfiguration: Optional[Dict[str, Any]] = Field(
        None,
        description='What the component configuration would have been if the update had succeeded.',
    )
    lastUpdateAttempt: Optional[str] = Field(
        None, description='Time of the latest failed update attempt.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Address(BaseModel):
    pipe: Optional[Pipe] = None
    socketAddress: Optional[SocketAddress] = None


class BuildVersion(BaseModel):
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Free-form build information. Envoy defines several well known keys in the source/common/version/version.h file',
    )
    version: Optional[SemanticVersion] = Field(
        None, description='SemVer version of extension.'
    )


class ClustersConfigDump(BaseModel):
    dynamicActiveClusters: Optional[List[DynamicCluster]] = Field(
        None,
        description='The dynamically loaded active clusters. These are clusters that are available to service data plane traffic.',
    )
    dynamicWarmingClusters: Optional[List[DynamicCluster]] = Field(
        None,
        description='The dynamically loaded warming clusters. These are clusters that are currently undergoing warming in preparation to service data plane traffic. Note that if attempting to recreate an Envoy configuration from a configuration dump, the warming clusters should generally be discarded.',
    )
    staticClusters: Optional[List[StaticCluster]] = Field(
        None, description='The statically loaded cluster configs.'
    )
    versionInfo: Optional[str] = Field(
        None,
        description='This is the :ref:`version_info ` in the last processed CDS discovery response. If there are only static bootstrap clusters, this field will be "".',
    )


class DoubleMatcher(BaseModel):
    exact: Optional[float] = Field(
        None,
        description='If specified, the input double value must be equal to the value specified here.',
    )
    range: Optional[DoubleRange] = Field(
        None,
        description='If specified, the input double value must be in the range specified here. Note: The range is using half-open interval semantics [start, end).',
    )


class DynamicListener(BaseModel):
    activeState: Optional[DynamicListenerState] = Field(
        None,
        description='The listener state for any active listener by this name. These are listeners that are available to service data plane traffic.',
    )
    drainingState: Optional[DynamicListenerState] = Field(
        None,
        description='The listener state for any draining listener by this name. These are listeners that are currently undergoing draining in preparation to stop servicing data plane traffic. Note that if attempting to recreate an Envoy configuration from a configuration dump, the draining listeners should generally be discarded.',
    )
    errorState: Optional[UpdateFailureState] = Field(
        None,
        description='Set if the last update failed, cleared after the next successful update.',
    )
    name: Optional[str] = Field(
        None,
        description='The name or unique id of this listener, pulled from the DynamicListenerState config.',
    )
    warmingState: Optional[DynamicListenerState] = Field(
        None,
        description='The listener state for any warming listener by this name. These are listeners that are currently undergoing warming in preparation to service data plane traffic. Note that if attempting to recreate an Envoy configuration from a configuration dump, the warming listeners should generally be discarded.',
    )


class Extension(BaseModel):
    category: Optional[str] = Field(
        None,
        description='Category of the extension. Extension category names use reverse DNS notation. For instance "envoy.filters.listener" for Envoy\'s built-in listener filters or "com.acme.filters.http" for HTTP filters from acme.com vendor. [#comment:',
    )
    disabled: Optional[bool] = Field(
        None,
        description='Indicates that the extension is present but was disabled via dynamic configuration.',
    )
    name: Optional[str] = Field(
        None,
        description='This is the name of the Envoy filter as specified in the Envoy configuration, e.g. envoy.filters.http.router, com.acme.widget.',
    )
    typeDescriptor: Optional[str] = Field(
        None,
        description='[#not-implemented-hide:] Type descriptor of extension configuration proto. [#comment:',
    )
    version: Optional[BuildVersion] = Field(
        None,
        description='The version is a property of the extension and maintained independently of other extensions and the Envoy API. This field is not set when extension did not provide version information.',
    )


class ListenersConfigDump(BaseModel):
    dynamicListeners: Optional[List[DynamicListener]] = Field(
        None, description='State for any warming, active, or draining listeners.'
    )
    staticListeners: Optional[List[StaticListener]] = Field(
        None, description='The statically loaded listener configs.'
    )
    versionInfo: Optional[str] = Field(
        None,
        description='This is the :ref:`version_info ` in the last processed LDS discovery response. If there are only static bootstrap listeners, this field will be "".',
    )


class Node(BaseModel):
    buildVersion: Optional[str] = Field(
        None,
        description='This is motivated by informing a management server during canary which version of Envoy is being tested in a heterogeneous fleet. This will be set by Envoy in management server RPCs. This field is deprecated in favor of the user_agent_name and user_agent_version values.',
    )
    clientFeatures: Optional[List[str]] = Field(
        None,
        description='Client feature support list. These are well known features described in the Envoy API repository for a given major version of an API. Client features use reverse DNS naming scheme, for example `com.acme.feature`. See :ref:`the list of features ` that xDS client may support.',
    )
    cluster: Optional[str] = Field(
        None,
        description='Defines the local service cluster name where Envoy is running. Though optional, it should be set if any of the following features are used: :ref:`statsd `, :ref:`health check cluster verification `, :ref:`runtime override directory `, :ref:`user agent addition `, :ref:`HTTP global rate limiting `, :ref:`CDS `, and :ref:`HTTP tracing `, either in this message or via :option:`--service-cluster`.',
    )
    extensions: Optional[List[Extension]] = Field(
        None, description='List of extensions and their versions supported by the node.'
    )
    id: Optional[str] = Field(
        None,
        description='An opaque node identifier for the Envoy node. This also provides the local service node name. It should be set if any of the following features are used: :ref:`statsd `, :ref:`CDS `, and :ref:`HTTP tracing `, either in this message or via :option:`--service-node`.',
    )
    listeningAddresses: Optional[List[Address]] = Field(
        None,
        description='Known listening ports on the node as a generic hint to the management server for filtering :ref:`listeners ` to be returned. For example, if there is a listener bound to port 80, the list can optionally contain the SocketAddress `(0.0.0.0,80)`. The field is optional and just a hint.',
    )
    locality: Optional[Locality] = Field(
        None, description='Locality specifying where the Envoy instance is running.'
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Opaque metadata extending the node identifier. Envoy will pass this directly to the management server.',
    )
    userAgentBuildVersion: Optional[BuildVersion] = Field(
        None, description='Structured version of the entity requesting config.'
    )
    userAgentName: Optional[str] = Field(
        None,
        description='Free-form string that identifies the entity requesting config. E.g. "envoy" or "grpc"',
    )
    userAgentVersion: Optional[str] = Field(
        None,
        description='Free-form string that identifies the version of the entity requesting config. E.g. "1.12.2" or "abcd1234", or "SpecialEnvoyBuild"',
    )


class RoutesConfigDump(BaseModel):
    dynamicRouteConfigs: Optional[List[DynamicRouteConfig]] = Field(
        None, description='The dynamically loaded route configs.'
    )
    staticRouteConfigs: Optional[List[StaticRouteConfig]] = Field(
        None, description='The statically loaded route configs.'
    )


class PerXdsConfig(BaseModel):
    clusterConfig: Optional[ClustersConfigDump] = None
    listenerConfig: Optional[ListenersConfigDump] = None
    routeConfig: Optional[RoutesConfigDump] = None
    scopedRouteConfig: Optional[ScopedRoutesConfigDump] = None
    status: Optional[Status] = None


class ClientConfig(BaseModel):
    node: Optional[Node] = Field(None, description='Node for a particular client.')
    xdsConfig: Optional[List[PerXdsConfig]] = None


class ClientStatusResponse(BaseModel):
    config: Optional[List[ClientConfig]] = Field(
        None,
        description='Client configs for the clients specified in the ClientStatusRequest.',
    )


class ClientStatusRequest(BaseModel):
    nodeMatchers: Optional[List[NodeMatcher]] = Field(
        None,
        description='Management server can use these match criteria to identify clients. The match follows OR semantics.',
    )


class ListMatcher(BaseModel):
    oneOf: Optional[ValueMatcher] = Field(
        None,
        description='If specified, at least one of the values in the list must match the value specified.',
    )


class NodeMatcher(BaseModel):
    nodeId: Optional[StringMatcher] = Field(
        None, description='Specifies match criteria on the node id.'
    )
    nodeMetadatas: Optional[List[StructMatcher]] = Field(
        None, description='Specifies match criteria on the node metadata.'
    )


class StructMatcher(BaseModel):
    path: Optional[List[PathSegment]] = Field(
        None, description='The path to retrieve the Value from the Struct.'
    )
    value: Optional[ValueMatcher] = Field(
        None,
        description='The StructMatcher is matched if the value retrieved by path is matched to this value.',
    )


class ValueMatcher(BaseModel):
    boolMatch: Optional[bool] = Field(
        None,
        description='If specified, a match occurs if and only if the target value is a bool value and is equal to this field.',
    )
    doubleMatch: Optional[DoubleMatcher] = Field(
        None,
        description='If specified, a match occurs if and only if the target value is a double value and is matched to this field.',
    )
    listMatch: Optional[ListMatcher] = Field(
        None,
        description='If specified, a match occurs if and only if the target value is a list value and is matched to this field.',
    )
    nullMatch: Optional[NullMatch] = Field(
        None,
        description='If specified, a match occurs if and only if the target value is a NullValue.',
    )
    presentMatch: Optional[bool] = Field(
        None,
        description='If specified, value match will be performed based on whether the path is referring to a valid primitive value in the metadata. If the path is referring to a non-primitive value, the result is always not matched.',
    )
    stringMatch: Optional[StringMatcher] = Field(
        None,
        description='If specified, a match occurs if and only if the target value is a string value and is matched to this field.',
    )


ClientStatusRequest.model_rebuild()
ListMatcher.model_rebuild()
NodeMatcher.model_rebuild()
StructMatcher.model_rebuild()
